include: package:very_good_analysis/analysis_options.yaml


analyzer:
  exclude:
    - "**/*.g.dart"
    - "**/*.gr.dart"
    - "**/*.freezed.dart"
    - "**/*.config.dart"
    - "**/l10n.dart"
  language:
    strict-raw-types: false

linter:
  rules:
    public_member_api_docs: false
    lines_longer_than_80_chars: false
    