include: package:very_good_analysis/analysis_options.yaml


analyzer:
  exclude:
    - "**/*.g.dart"
    - "**/*.gr.dart"
    - "**/*.freezed.dart"
    - "**/*.config.dart"
    - "**/l10n.dart"


linter:
  rules:
    public_member_api_docs: false


