name: the_quote

packages:
  - packages/**

scripts:
  clean: melos exec -- flutter clean

  get:
    run: |
      melos exec -- flutter pub get
    description: Run 'packages get' in all packages.

  check_versions:
    run: |
      melos exec -- ruby ../../scripts/check_dependencies/check.rb
    description: Checks wheather all packages have same packages versions

  analyze:
    run: melos exec -- flutter analyze --no-fatal-infos --no-fatal-warnings
    description: Run 'dart analyze' in all packages.

  generate:
    run: |
      melos exec -- flutter pub run build_runner build --delete-conflicting-outputs
    description: Generate files in all packages.
    packageFilters:
      dependsOn:
        - build_runner

  generate_l10n:
    run: |
      melos exec -- flutter pub run easy_localization:generate -S assets/translations -O lib/core/l10n -f keys -o locale_keys.g.dart
    description: Generate translations keys in all packages.
    packageFilters:
      dependsOn:
        - easy_localization