name: the_quote

packages:
  - packages/**

command:
  bootstrap:
    usePubspecOverrides: true

scripts:
  clean: melos exec -- flutter clean

  get:
    run: melos exec -- flutter pub get
    description: Run 'packages get' in all packages.


  analyze:
    run: melos exec -- flutter analyze --no-fatal-infos --no-fatal-warnings
    description: Run 'dart analyze' in all packages.

  gen:
    run: flutter packages pub run build_runner build -d
    packageFilters:
      dependsOn: 'build_runner'


  generate_l10n:
    run:  flutter pub run easy_localization:generate -S assets/translations -O lib/core/l10n -f keys -o locale_keys.g.dart
    name: Generate translations keys in all packages.