name: the_quote
description: A new Flutter project.
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  bloc: ^8.1.2
  easy_localization: ^3.0.2
  firebase_core: ^2.13.0
  flex_color_scheme: ^7.2.0
  flutter:
    sdk: flutter
  flutter_bloc: ^8.1.3
  flutter_svg: ^2.0.6
  freezed_annotation: ^2.2.0
  get_it: ^7.6.0
  go_router: ^7.1.1
  injectable: ^2.1.1
  json_annotation: ^4.8.1



dev_dependencies:
  build_runner: ^2.4.4
  flutter_lints: ^2.0.0
  flutter_test:
    sdk: flutter
  freezed: ^2.3.4
  injectable_generator: ^2.1.5
  json_serializable: ^6.7.0
  very_good_analysis: ^5.0.0+1



flutter:
  assets:
    - assets/icons/
    - assets/translations/
  uses-material-design: true
  fonts:
    - family: SourceSerifPro
      fonts:
        - asset: assets/fonts/source_serif_pro/SourceSerifPro-ExtraLight.ttf
          weight: 200
        - asset: assets/fonts/source_serif_pro/SourceSerifPro-Light.ttf
          weight: 300
        - asset: assets/fonts/source_serif_pro/SourceSerifPro-Regular.ttf
          weight: 400
        - asset: assets/fonts/source_serif_pro/SourceSerifPro-SemiBold.ttf
          weight: 600
        - asset: assets/fonts/source_serif_pro/SourceSerifPro-Bold.ttf
          weight: 700
        - asset: assets/fonts/source_serif_pro/SourceSerifPro-Black.ttf
          weight: 900
    - family: Montserrat
      fonts:
        - asset: assets/fonts/montserrat/Montserrat-Thin.ttf
          weight: 100
        - asset: assets/fonts/montserrat/Montserrat-ExtraLight.ttf
          weight: 200
        - asset: assets/fonts/montserrat/Montserrat-Light.ttf
          weight: 300
        - asset: assets/fonts/montserrat/Montserrat-Regular.ttf
          weight: 400
        - asset: assets/fonts/montserrat/Montserrat-Medium.ttf
          weight: 500
        - asset: assets/fonts/montserrat/Montserrat-SemiBold.ttf
          weight: 600
        - asset: assets/fonts/montserrat/Montserrat-Bold.ttf
          weight: 700
        - asset: assets/fonts/montserrat/Montserrat-ExtraBold.ttf
          weight: 800
        - asset: assets/fonts/montserrat/Montserrat-Black.ttf
          weight: 900



