name: the_quote
description: A new Flutter project.
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  firebase_core: ^2.13.0
  flutter:
    sdk: flutter
  get_it: ^7.6.0
  injectable: ^2.1.1
  the_quote_core_ui:
    path: ../the_quote_core_ui/
  the_quote_localization:
    path: ../the_quote_localization/


dev_dependencies:
  build_runner: ^2.4.4
  flutter_lints: ^2.0.0
  flutter_test:
    sdk: flutter
  injectable_generator: ^2.1.5
  very_good_analysis: ^5.0.0+1



flutter:
  uses-material-design: true


